[2025-08-17 15:08:42] 🟢 프로그램 시작
[2025-08-17 15:17:34] 🟢 프로그램 시작
[2025-08-17 15:17:34] 🟡 prevConfig.json이 없습니다. 초기 설정을 진행합니다.
[2025-08-17 15:17:38] 🟢 초기 설정 완료: prevConfig.json 생성됨
[2025-08-17 15:18:57] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\paul\Desktop\dev\파이썬qt\app\main.py", line 187, in <module>
    except:
    
KeyboardInterrupt

[2025-08-17 15:20:02] 🟢 프로그램 시작
[2025-08-17 15:20:11] 🟢 프로그램 시작
[2025-08-17 15:20:22] 🟢 초기 설정 완료: prevConfig.json 생성됨
[2025-08-17 15:20:30] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-17 15:21:43] 🟢 프로그램 시작
[2025-08-17 15:23:58] 🟢 프로그램 시작
[2025-08-17 15:24:20] 🟢 프로그램 시작
[2025-08-17 15:25:02] 🟢 프로그램 시작
[2025-08-17 15:25:21] 🟢 프로그램 시작
[2025-08-17 15:27:55] 🟢 프로그램 시작
[2025-08-17 15:28:01] 🟢 5개 파일 선택됨
[2025-08-17 15:29:57] 🟢 프로그램 시작
[2025-08-17 15:31:31] 🟢 프로그램 시작
[2025-08-17 15:33:27] 🟢 프로그램 시작
[2025-08-17 15:33:54] 🟢 프로그램 시작
[2025-08-17 15:34:25] 🟢 프로그램 시작
[2025-08-17 15:37:52] 🟢 프로그램 시작
[2025-08-17 15:39:20] 🟢 프로그램 시작
[2025-08-17 15:39:48] 🟢 프로그램 시작
[2025-08-17 15:40:40] 🟢 프로그램 시작
[2025-08-17 15:40:44] 🟢 프로그램 시작
[2025-08-17 15:43:54] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\paul\Desktop\dev\파이썬qt\app\main.py", line 299, in <module>
    close_btn.clicked.connect(dialog.accept)
         ^^^^^^^^^^
KeyboardInterrupt

[2025-08-17 15:43:57] 🟢 프로그램 시작
[2025-08-18 11:11:21] 🟢 프로그램 시작
[2025-08-18 11:11:49] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 193, in run_copy
    final_target = copy_images(file_names, source, target, self.log)
  File "C:\Users\myh\Desktop\dev\copyImage\app\copy_utils.py", line 7, in copy_images
    os.makedirs(target_dir, exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 227, in makedirs
PermissionError: [WinError 5] 액세스가 거부되었습니다: 'C:/Users/paul'

[2025-08-18 11:12:05] ❌ 예외 발생:
Traceback (most recent call last):
  File "C:\Users\myh\Desktop\dev\copyImage\app\main.py", line 193, in run_copy
    final_target = copy_images(file_names, source, target, self.log)
  File "C:\Users\myh\Desktop\dev\copyImage\app\copy_utils.py", line 7, in copy_images
    os.makedirs(target_dir, exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 217, in makedirs
  File "<frozen os>", line 227, in makedirs
PermissionError: [WinError 5] 액세스가 거부되었습니다: 'C:/Users/paul'

[2025-08-18 11:12:23] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-18 11:12:26] 🟢 prevConfig.json 내용을 불러왔습니다
[2025-08-18 11:13:28] 🟢 4개 파일 선택됨
[2025-08-18 11:13:29] 📁 대상 폴더 생성: C:/Users/myh/Desktop/오답노트2
[2025-08-18 11:13:29] ✅ 복사됨: mr2 (1) (1).PNG
[2025-08-18 11:13:29] ✅ 복사됨: mr2 (1).PNG
[2025-08-18 11:13:29] ✅ 복사됨: mr1 (11).PNG
[2025-08-18 11:13:29] ✅ 복사됨: mr1 (10).PNG
[2025-08-18 11:13:29] ✅ 작업 완료!
